-- Billing module schema
CREATE TABLE invoices (
    id              UUID PRIMARY KEY,
    tenant_id       UUID NOT NULL,
    invoice_number  VARCHAR(40) NOT NULL,
    branch_id       UUID NOT NULL,
    customer_id     UUID NOT NULL,
    invoice_date    DATE NOT NULL,
    due_date        DATE,
    type            VARCHAR(20) NOT NULL DEFAULT 'SALE',
    place_of_supply VARCHAR(60),
    is_interstate   BOOLEAN NOT NULL DEFAULT FALSE,
    subtotal        NUMERIC(16,2),
    making_total    NUMERIC(16,2),
    discount_total  NUMERIC(16,2),
    taxable_amount  NUMERIC(16,2),
    cgst_amount     NUMERIC(16,2),
    sgst_amount     NUMERIC(16,2),
    igst_amount     NUMERIC(16,2),
    round_off       NUMERIC(8,2),
    grand_total     NUMERIC(16,2),
    paid_amount     NUMERIC(16,2),
    balance_amount  NUMERIC(16,2),
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    remarks         VARCHAR(500),
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    created_by      UUID NOT NULL,
    updated_by      UUID NOT NULL,
    version         BIGINT,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    custom_fields   JSONB DEFAULT '{}'::jsonb,
    CONSTRAINT uk_inv_no UNIQUE (tenant_id, invoice_number)
);
CREATE INDEX ix_inv_status ON invoices(tenant_id, status);
CREATE INDEX ix_inv_customer ON invoices(tenant_id, customer_id);

CREATE TABLE invoice_lines (
    id             UUID PRIMARY KEY,
    tenant_id      UUID NOT NULL,
    invoice_id     UUID NOT NULL,
    line_no        INT NOT NULL,
    item_desc      VARCHAR(200),
    hsn_code       VARCHAR(20),
    lot_id         UUID,
    product_id     UUID,
    gross_weight   NUMERIC(14,4),
    fineness       NUMERIC(7,3),
    pure_weight    NUMERIC(14,4),
    rate_per_gram  NUMERIC(14,2),
    metal_value    NUMERIC(16,2),
    making_charges NUMERIC(16,2),
    discount       NUMERIC(16,2),
    taxable_amount NUMERIC(16,2),
    tax_rate_pct   NUMERIC(5,2),
    cgst_amount    NUMERIC(16,2),
    sgst_amount    NUMERIC(16,2),
    igst_amount    NUMERIC(16,2),
    line_total     NUMERIC(16,2),
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    created_by     UUID NOT NULL,
    updated_by     UUID NOT NULL,
    version        BIGINT,
    is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    custom_fields  JSONB DEFAULT '{}'::jsonb
);
CREATE INDEX ix_il_invoice ON invoice_lines(invoice_id);

CREATE TABLE invoice_payments (
    id             UUID PRIMARY KEY,
    tenant_id      UUID NOT NULL,
    invoice_id     UUID NOT NULL,
    payment_date   DATE NOT NULL,
    amount         NUMERIC(16,2) NOT NULL,
    method         VARCHAR(20) NOT NULL DEFAULT 'CASH',
    reference_no   VARCHAR(80),
    remarks        VARCHAR(300),
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    created_by     UUID NOT NULL,
    updated_by     UUID NOT NULL,
    version        BIGINT,
    is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    custom_fields  JSONB DEFAULT '{}'::jsonb
);
CREATE INDEX ix_ip_invoice ON invoice_payments(invoice_id);
